/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report that the process can serve HTTP
         * @description Depends on nothing else, so that an outage elsewhere does not cause this process to be restarted when restarting it would not help.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The process is serving. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report that the platform can do its work
         * @description The record is reachable, the schema is the one this build expects, and stored bytes can be reached. A build whose migrations have not been applied is deliberately not ready.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ready?: boolean;
                            checks?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description Not ready. The body says which check failed. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ready?: boolean;
                            checks?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identify the build serving this request */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The build. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name?: string;
                            service?: string;
                            version?: string;
                            commit?: string;
                            builtAt?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description An unknown address and a wrong secret are refused identically, so the response cannot be used to discover who is registered.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        secret: string;
                    };
                };
            };
            responses: {
                /** @description A session, in a cookie the browser cannot read from script and in the body for programmatic clients. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                            /** Format: date-time */
                            expiresAt?: string;
                            principal?: components["schemas"]["Principal"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        /** Sign out */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report who the caller is */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller and the institutions whose bindings apply to them. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            principal?: components["schemas"]["Principal"];
                            organisations?: components["schemas"]["Organisation"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/denials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the refusals the caller has received
         * @description Why access was denied is data, not a log line.
         *
         */
        get: {
            parameters: {
                query?: {
                    /** @description How many to return. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recent refusals. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            denials?: components["schemas"]["Denial"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Found an institution
         * @description It is created holding contributor at its own scope, so that its members can do its work without a separate grant each.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        slug: string;
                        name: string;
                    };
                };
            };
            responses: {
                /** @description The institution. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organisation"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add someone who can sign in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        displayName: string;
                        /** Format: email */
                        email: string;
                        secret: string;
                    };
                };
            };
            responses: {
                /** @description The person. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Principal"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bind a role at the platform, an institution, or the work queue
         * @description Grants on a city are made by that city's stewards instead.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        subjectKind: "principal" | "org";
                        subjectId: string;
                        /** @enum {string} */
                        scopeKind: "platform" | "org" | "city" | "work";
                        scopeId?: string;
                        role: components["schemas"]["Role"];
                    };
                };
            };
            responses: {
                /** @description The binding. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Binding"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisations/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an institution and its members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The institution. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            organisation?: components["schemas"]["Organisation"];
                            members?: components["schemas"]["Principal"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisations/{orgId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a member
         * @description Membership makes the institution's bindings apply to that person; it grants nothing itself.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        principalId: string;
                    };
                };
            };
            responses: {
                /** @description Done. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisations/{orgId}/members/{principalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                    /** @description The person. */
                    principalId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisations/{orgId}/service-principals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a worker, edge station, or vehicle
         * @description The credential is shown once and is not recoverable; it can only be replaced.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        displayName: string;
                    };
                };
            };
            responses: {
                /** @description The principal and its credential. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            principal?: components["schemas"]["Principal"];
                            credential?: string;
                            notice?: string;
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisations/{orgId}/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report what an institution may consume and what it does
         * @description Reading this before submitting is how a refusal becomes understandable in advance.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The quota and what is in flight. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            quota?: components["schemas"]["Quota"];
                            inUse?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /** State what an institution may consume */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        maxConcurrentJobs: number;
                        maxCpu: number;
                        /** Format: int64 */
                        maxMemoryBytes: number;
                        maxGpu?: number;
                    };
                };
            };
            responses: {
                /** @description The quota. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Quota"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the places work can run */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The targets. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            targets?: components["schemas"]["Target"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Record a place work can run */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** @enum {string} */
                        kind: "local_docker" | "kubernetes" | "slurm";
                        capacityCpu: number;
                        /** Format: int64 */
                        capacityMemoryBytes: number;
                        capacityGpu?: number;
                    };
                };
            };
            responses: {
                /** @description The target. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Target"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the places the caller may learn of
         * @description An unlisted place appears only to those bound to it; it is otherwise indistinguishable from a place that does not exist.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The catalogue. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cities?: components["schemas"]["City"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        /** Found a place */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        slug: string;
                        name: string;
                        summary: string;
                        extent: components["schemas"]["Extent"];
                        crsEpsg: number;
                        verticalDatum: string;
                        discoverability: components["schemas"]["Discoverability"];
                    };
                };
            };
            responses: {
                /** @description The place. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["City"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{cityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enter a place */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The place. */
                    cityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The place and the caller's authority in it. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            city?: components["schemas"]["City"];
                            you?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a place's description or who may learn of it
         * @description Its extent, coordinate reference, and vertical datum are what the place is, and are not changed here.
         *
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The place. */
                    cityId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        summary?: string;
                        discoverability?: components["schemas"]["Discoverability"];
                    };
                };
            };
            responses: {
                /** @description The place. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["City"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/cities/{cityId}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List who has been granted access to a place */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The place. */
                    cityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The grants. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            grants?: components["schemas"]["Binding"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Share a place
         * @description Nothing is copied: a grant is an edge, and revoking it takes effect on the next request.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The place. */
                    cityId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        subjectKind: "principal" | "org";
                        subjectId: string;
                        role: components["schemas"]["Role"];
                    };
                };
            };
            responses: {
                /** @description The grant. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Binding"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{cityId}/grants/{bindingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Withdraw access to a place */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The place. */
                    cityId: string;
                    /** @description The grant. */
                    bindingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{cityId}/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the layers of a place
         * @description A layer holding nothing the caller may see does not appear.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The place. */
                    cityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The layers. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            layers?: components["schemas"]["Layer"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Contribute a layer to a place
         * @description It is contained by that scope and attributed to the institution named, which must be one the caller may act for.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The place. */
                    cityId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        slug: string;
                        kind: string;
                        title: string;
                        description: string;
                        attributedOrgId: string;
                    };
                };
            };
            responses: {
                /** @description The layer. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Layer"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/world/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the layers of the shared world
         * @description A layer holding nothing the caller may see does not appear.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The layers. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            layers?: components["schemas"]["Layer"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Contribute a layer to the shared world
         * @description It is contained by that scope and attributed to the institution named, which must be one the caller may act for.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        slug: string;
                        kind: string;
                        title: string;
                        description: string;
                        attributedOrgId: string;
                    };
                };
            };
            responses: {
                /** @description The layer. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Layer"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a layer and the versions the caller may see */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The layer. */
                    layerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The layer and its versions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            layer?: components["schemas"]["Layer"];
                            versions?: components["schemas"]["Version"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layerId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record evidence
         * @description Everything a version must state is required: a coordinate reference, a vertical datum, a time basis, rights, attribution, and an uncertainty — of which "unknown" is a legal answer and absence is not. A version derived from a scenario cannot claim a stronger truth class.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The layer. */
                    layerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VersionRequest"];
                };
            };
            responses: {
                /** @description The version. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layerId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The layer. */
                    layerId: string;
                    /** @description The version. */
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version?: components["schemas"]["Version"];
                            uncertainty?: components["schemas"]["Uncertainty"];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layerId}/versions/{versionId}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report what a version was derived from
         * @description This is what makes a claim traceable to the material behind it.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The layer. */
                    layerId: string;
                    /** @description The version. */
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The inputs. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            derivedFrom?: components["schemas"]["Version"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layerId}/versions/{versionId}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one file of a version
         * @description Access to bytes follows access to the evidence that contains them, so a caller who may not see the version cannot reach its bytes by knowing an object identifier.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The layer. */
                    layerId: string;
                    /** @description The version. */
                    versionId: string;
                    /** @description The file's path within the version. */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The file and a short-lived URL to read it. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            file?: components["schemas"]["ManifestFile"];
                            readUrl?: string;
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layerId}/versions/{versionId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Offer a draft for review
         * @description Only a draft can be offered.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The layer. */
                    layerId: string;
                    /** @description The version. */
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description The version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layerId}/versions/{versionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a reviewed version
         * @description Publishing a version that supersedes another marks the earlier one superseded in the same transaction.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The layer. */
                    layerId: string;
                    /** @description The version. */
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description The version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layerId}/versions/{versionId}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make a contribution part of the shared record
         * @description Nothing moves: the object keys, the content digest, and the version number are unchanged. Only who may see it changes.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The layer. */
                    layerId: string;
                    /** @description The version. */
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description The version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/layers/{layerId}/versions/{versionId}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw a published version from default views
         * @description It is not deleted, and neither is its lineage: retraction is a statement about a version, not its erasure.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The layer. */
                    layerId: string;
                    /** @description The version. */
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description The version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisations/{orgId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain a grant to place bytes in storage
         * @description What the caller claims about those bytes is written down now, so that it can be checked against what actually arrives.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        bucket: "evidence" | "derived" | "ephemeral";
                        sha256: string;
                        /** Format: int64 */
                        sizeBytes: number;
                        mediaType: string;
                    };
                };
            };
            responses: {
                /** @description The grant. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadGrant"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisations/{orgId}/uploads/{grantId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check what arrived against what was declared
         * @description Bytes that are not what they said they were are discarded and nothing is recorded.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                    /** @description The grant. */
                    grantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description The recorded object. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Object"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisations/{orgId}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an institution's work */
        get: {
            parameters: {
                query?: {
                    /** @description How many to return. */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The work. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            jobs?: components["schemas"]["Job"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Ask the platform to run work
         * @description The image is pinned by digest. Whether there is room is decided by the broker, which records either answer.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution. */
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        recipeId: string;
                        imageDigest: string;
                        command: string[];
                        args?: string[];
                        inputs?: components["schemas"]["JobInput"][];
                        outputs?: components["schemas"]["JobOutput"][];
                        requestCpu: number;
                        /** Format: int64 */
                        requestMemoryBytes: number;
                        requestGpu?: number;
                        walltimeSeconds: number;
                    };
                };
            };
            responses: {
                /** @description The admitted work. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["Refused"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one job, its attempts, and what it produced
         * @description The attempts are what show that a retry happened and what came of it.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The job. */
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The job. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            job?: components["schemas"]["Job"];
                            attempts?: components["schemas"]["Attempt"][];
                            outputs?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a job's durable account of itself
         * @description Resuming from a sequence number is how a client watches without missing or repeating anything.
         *
         */
        get: {
            parameters: {
                query?: {
                    /** @description The sequence number to resume from. */
                    after?: number;
                    /** @description How many to return. */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description The job. */
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The events. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            events?: components["schemas"]["JobEvent"][];
                        };
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop work that has not finished
         * @description Running work learns of this through its worker's next heartbeat.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The job. */
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description The job. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take one admitted job
         * @description A worker holds authority over the work queue and over nothing else. Everything it reaches while running a job, it reaches through this lease.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        targetName: string;
                    };
                };
            };
            responses: {
                /** @description The lease. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lease"];
                    };
                };
                /** @description Done. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work/{attemptId}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extend a lease and learn whether to stop */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The attempt. */
                    attemptId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description The lease's new expiry, and whether the work was cancelled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Heartbeat"];
                    };
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work/{attemptId}/started": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report that the container is running */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The attempt. */
                    attemptId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        placementRef?: string;
                    };
                };
            };
            responses: {
                /** @description Done. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work/{attemptId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report progress */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The attempt. */
                    attemptId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        detail?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Done. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work/{attemptId}/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read one input of leased work */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The attempt. */
                    attemptId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        name: string;
                    };
                };
            };
            responses: {
                /** @description The input and a short-lived URL to read it. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            input?: components["schemas"]["JobInput"];
                            readUrl?: string;
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work/{attemptId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain a grant to place one output in storage
         * @description The size the job declared bounds what may be uploaded, so oversized output is refused before any bytes move.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The attempt. */
                    attemptId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        name: string;
                        sha256: string;
                        /** Format: int64 */
                        sizeBytes: number;
                    };
                };
            };
            responses: {
                /** @description The grant. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadGrant"];
                    };
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work/{attemptId}/uploads/{grantId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check one output against what was declared */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The attempt. */
                    attemptId: string;
                    /** @description The grant. */
                    grantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description The recorded object. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Object"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work/{attemptId}/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record one file the work produced
         * @description An output is recorded once per name however many attempts a job takes.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The attempt. */
                    attemptId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        name: string;
                        objectId: string;
                    };
                };
            };
            responses: {
                /** @description Done. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work/{attemptId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report how an attempt ended */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The attempt. */
                    attemptId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        /** @enum {string} */
                        outcome: "succeeded" | "failed" | "cancelled" | "evicted" | "timed_out";
                        exitCode?: number;
                        failureClass?: string;
                    };
                };
            };
            responses: {
                /** @description The job. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                400: components["responses"]["Invalid"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            error: {
                /** @description A stable identifier for the kind of failure. */
                code: string;
                /** @description What went wrong, written for the person who will read it. */
                message: string;
                /** @description Ties this failure to every record written while serving the request. */
                requestId: string;
                detail?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @description A bounded region of the globe, in WGS 84 degrees. */
        Extent: {
            west: number;
            south: number;
            east: number;
            north: number;
        };
        /**
         * @description What a value is, epistemically. It travels down lineage and is never strengthened: anything derived from a scenario is a scenario.
         *
         * @enum {string}
         */
        TruthClass: "observation" | "analysis" | "forecast" | "scenario" | "simulation";
        /**
         * @description What a principal with no binding may learn about a place. Separate from whether that principal may enter it.
         *
         * @enum {string}
         */
        Discoverability: "listed_open" | "listed_locked" | "unlisted";
        /** @enum {string} */
        Role: "viewer" | "contributor" | "steward" | "admin";
        /** @description What a version does not know. "unknown" is an answer; absence is not.
         *      */
        Uncertainty: {
            /** @enum {string} */
            kind: "unknown" | "absolute_metres" | "relative_fraction" | "described";
            /** @description Required for absolute_metres and relative_fraction; absent otherwise. */
            value?: number;
            /** @description Required for described. */
            note?: string;
        };
        Principal: {
            id: string;
            /** @enum {string} */
            kind: "person" | "service";
            displayName: string;
            email?: string;
            orgId?: string;
            disabled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        Organisation: {
            id: string;
            slug: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description A bounded, curated, navigable place. It exists at the platform and is addressed permanently; an organisation is granted access to it and never contains it.
         *      */
        City: {
            id: string;
            slug: string;
            name: string;
            summary: string;
            extent: components["schemas"]["Extent"];
            crsEpsg: number;
            verticalDatum: string;
            discoverability: components["schemas"]["Discoverability"];
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
        };
        /** @description A named series of versions within one scope. Contained by the platform or by a city; attributed to the organisation that contributed it.
         *      */
        Layer: {
            id: string;
            /** @enum {string} */
            scopeKind: "platform" | "city";
            cityId?: string;
            slug: string;
            /** @enum {string} */
            kind: "bathymetry" | "mesh" | "point_cloud" | "orthomosaic" | "structure" | "field" | "observation_series" | "annotation" | "telemetry" | "tileset" | "imagery";
            title: string;
            description: string;
            attributedOrgId: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        ManifestFile: {
            relativePath: string;
            objectId: string;
            sha256: string;
            /** Format: int64 */
            sizeBytes: number;
            mediaType: string;
        };
        /** @description Immutable evidence: what was measured or computed, where, when, by what, and how well it is known.
         *      */
        Version: {
            id: string;
            layerId: string;
            ordinal: number;
            /** @description The digest over this version's whole manifest, and its citable identity. */
            contentDigest: string;
            truthClass: components["schemas"]["TruthClass"];
            crsEpsg: number;
            verticalDatum: string;
            extent: components["schemas"]["Extent"];
            /** Format: date-time */
            observedFrom: string;
            /** Format: date-time */
            observedTo: string;
            /** @description The instrument clock's offset from UTC, where it was determined. */
            clockOffsetSeconds?: number;
            rights: string;
            attribution: string;
            /** @enum {string} */
            state: "draft" | "in_review" | "published" | "superseded" | "retracted";
            /** @enum {string} */
            visibility: "restricted" | "canonical";
            supersedesId?: string;
            supersededById?: string;
            producerJobId?: string;
            producerPrincipalId?: string;
            recipeId?: string;
            imageDigest?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: date-time */
            retractedAt?: string;
            retractionReason?: string;
            manifest?: components["schemas"]["ManifestFile"][];
        };
        VersionRequest: {
            truthClass: components["schemas"]["TruthClass"];
            crsEpsg: number;
            verticalDatum: string;
            extent: components["schemas"]["Extent"];
            /** Format: date-time */
            observedFrom: string;
            /** Format: date-time */
            observedTo: string;
            clockOffsetSeconds?: number;
            uncertainty: components["schemas"]["Uncertainty"];
            rights: string;
            attribution: string;
            /** @enum {string} */
            visibility?: "restricted" | "canonical";
            files: {
                relativePath: string;
                objectId: string;
            }[];
            /** @description The versions this one was computed from. Their truth classes bound what it may claim. */
            derivedFrom?: string[];
            supersedesId?: string;
        };
        Binding: {
            id: string;
            /** @enum {string} */
            subjectKind: "principal" | "org";
            subjectId: string;
            /** @enum {string} */
            scopeKind: "platform" | "org" | "city" | "work";
            scopeId?: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            revokedAt?: string;
        };
        Object: {
            id: string;
            /** @enum {string} */
            bucket: "evidence" | "derived" | "ephemeral";
            sha256: string;
            /** Format: int64 */
            sizeBytes: number;
            mediaType: string;
            uploadedBy: string;
            /** Format: date-time */
            uploadedAt: string;
        };
        UploadGrant: {
            id: string;
            /** @enum {string} */
            bucket: "evidence" | "derived" | "ephemeral";
            /** @description A short-lived URL accepting exactly one upload. It is signed over its host, so it names the address this caller can reach.
             *      */
            uploadUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        JobInput: {
            name: string;
            relativePath: string;
            objectId: string;
            sha256: string;
            mediaType: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        JobOutput: {
            name: string;
            relativePath: string;
            mediaType: string;
            /** Format: int64 */
            maxSizeBytes: number;
        };
        Job: {
            id: string;
            orgId: string;
            submittedBy: string;
            recipeId: string;
            /** @description Pinned by digest. A tag can be moved and proves nothing. */
            imageDigest: string;
            command: string[];
            args?: string[];
            inputs?: components["schemas"]["JobInput"][];
            outputs?: components["schemas"]["JobOutput"][];
            requestCpu: number;
            /** Format: int64 */
            requestMemoryBytes: number;
            requestGpu?: number;
            walltimeSeconds: number;
            targetId?: string;
            /** @enum {string} */
            state: "pending" | "admitted" | "running" | "succeeded" | "failed" | "cancelled" | "evicted" | "timed_out";
            /** @enum {string} */
            failureClass: "none" | "image_unavailable" | "input_unavailable" | "output_limit_exceeded" | "nonzero_exit" | "walltime_exceeded" | "worker_lost" | "cancelled_by_caller" | "internal_error";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            terminalAt?: string;
        };
        /** @description One placement of a job onto a target. Retries create attempts, never new jobs. */
        Attempt: {
            id: string;
            jobId: string;
            ordinal: number;
            targetId: string;
            workerId: string;
            /** @enum {string} */
            state: "leased" | "running" | "succeeded" | "failed" | "cancelled" | "evicted" | "timed_out";
            /** Format: date-time */
            leaseExpiresAt: string;
            placementRef?: string;
            exitCode?: number;
            failureClass: string;
            /** Format: date-time */
            leasedAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        /** @description One entry in a job's durable, ordered account of itself. */
        JobEvent: {
            id: string;
            jobId: string;
            attemptId?: string;
            /** Format: int64 */
            sequence: number;
            /** Format: date-time */
            occurredAt: string;
            /** @enum {string} */
            kind: "admitted" | "scheduled" | "started" | "progress" | "output_received" | "succeeded" | "failed" | "cancelled" | "evicted" | "timed_out";
            detail: {
                [key: string]: unknown;
            };
        };
        Target: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "local_docker" | "kubernetes" | "slurm";
            enabled: boolean;
            capacityCpu: number;
            /** Format: int64 */
            capacityMemoryBytes: number;
            capacityGpu: number;
            /** Format: date-time */
            createdAt: string;
        };
        Quota: {
            orgId: string;
            maxConcurrentJobs: number;
            maxCpu: number;
            /** Format: int64 */
            maxMemoryBytes: number;
            maxGpu: number;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description A recorded refusal, so that "why can I not see this" is answerable from data. */
        Denial: {
            id: string;
            /** Format: date-time */
            occurredAt: string;
            principalId?: string;
            action: string;
            resourceKind: string;
            resourceId?: string;
            /** @enum {string} */
            effect: "hidden" | "visible";
            reason: string;
            requestId: string;
        };
        Lease: {
            attemptId: string;
            token: string;
            /** Format: date-time */
            expiresAt: string;
            job: components["schemas"]["Job"];
        };
        Heartbeat: {
            /** Format: date-time */
            expiresAt: string;
            /** @description Tells the worker to stop. This is how cancellation reaches running work. */
            cancelled: boolean;
        };
    };
    responses: {
        /** @description No credentials, or credentials that identify nobody. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The object exists and the caller may not act on it. `detail.accessMayBeRequested` marks refusals where asking is the next step.
         *      */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Nothing the caller is entitled to know about. An unlisted place is reported this way whether or not it exists.
         *      */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The request describes something that cannot exist. */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The record refuses this because of what it already holds. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Well-formed, but refused on its meaning: bytes that are not what was declared, or a truth class stronger than its lineage allows.
         *      */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Work the platform declined to admit. The code names the reason and the refusal is recorded.
         *      */
        Refused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
